title: AI from Cosmology to Everywhere
description: AI, data science, inflation, cosmology, physics, maths
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
